### PR TITLE
Add example of how to use bootstrap-sass

### PR DESCRIPTION
**Pull request by retlehs**
* Introduce `main.scss.example`
* Add `bootstrap-sass-official` asset overrides to `bower.json`

* * *

How to get started using Bootstrap Sass:

1. Run `bower install bootstrap-sass-official --save`
2. Rename `main.scss.example` file to `main.scss` and remove `main.less`
3. Update the `assets/manifest.json` styles dependencies to change `main.less` to `main.scss`

### CODE REVIEW

**Comment by retlehs** [comment]
when the gulp branch is merged into master, [roots-sass](https://github.com/roots/roots-sass) is going to be deprecated in favor of this method

this method is also **temporary**, as the upcoming roots generator will handle this a lot more elegantly

**Comment by DevinWalker** [comment]
Upcoming Roots Generator?! Please, do tell more... I'm chomping at the bit to get Roots + Gulp + SASS in my arsenal.

**Comment by retlehs** [comment]
see the 3 steps at the top of this PR (make sure you're using the  `8.0.0` branch)

**Comment by austinpray** [comment]
@DevinWalker 8.0.0 branch is ready to roll as of right now to work with Sass just remove all the less files and point the manifest.json to your main.scss

**Pull request merged**
