### PR TITLE
Sage 8.0.0

### PR DESCRIPTION
**Pull request by retlehs**
8.0.0 development is being done on the [8.0.0 branch](https://github.com/roots/roots/tree/8.0.0). let's hold off on any commits to master **unless they're necessary** :warning:

check out the [CHANGELOG](https://github.com/roots/roots/blob/8.0.0/CHANGELOG.md) and the [README](https://github.com/roots/roots/blob/8.0.0/README.md)

* ref #1138 — grunt -> gulp
* ref #1247 — rename theme from roots to sage
* ref #1267 — bump reqs to php 5.4, use short echo syntax
* ref #1268 — use short array syntax
* ref #1279 — coding standards

Also check out https://github.com/austinpray/asset-builder/issues to help improve the new asset manifest. Any contributions over there will improve Sage 8.0.0 as well.

### todo 

* [x] Document Manifest.json Specification https://github.com/austinpray/asset-builder/issues/5
* [x] Document Manifest Usage Example https://github.com/austinpray/asset-builder/issues/6
* [x] roots.pot -> sage.pot (@retlehs)
* [ ] rename roots-translations repo (@retlehs)
* [ ] deprecate roots-sass (@retlehs)
* [x] coding standards (#1176, #1279)
* [x] PHP_CodeSniffer integrated in CI (#1279)
* [x] update google analytics condition ([discourse thread](http://discourse.roots.io/t/google-analytics-condition-seems-off/2778))
* [x] remove lodash from package.json and gulpfile (it isn't currently being used).

### CODE REVIEW

**Comment by austinpray** [comment]
I like "globs" better the "mix" so I closed that.

**Comment by austinpray** [comment]
@JulienMelissas @retlehs so is the watch task working for you guys again? If so can I close "gulp - livereload on assets" ?

**Comment by mAAdhaTTah** [comment]
I've never been this excited about a pull request before!

**Comment by conatus** [comment]
Hi guys - interested in starting to work on a theme but don't want to until this PR is merged. 

Are there any tasks I can get stuck in with to expedite the merge or is this branch usable right now as a basis?

**Comment by retlehs** [comment]
related: https://discourse.roots.io/t/is-8-0-0-ready-enough/2559

at this point, this branch is pretty stable (imo). there shouldn't be any major changes between now and final release, but you might have to make a few adjustments to the gulpfile if you clone now

**Comment by JulienMelissas** [comment]
Yep I can confirm I'm using it on a job right now and it's working fine.

On Thursday, February 19, 2015, Ben Word <notifications@github.com> wrote:

> related: https://discourse.roots.io/t/is-8-0-0-ready-enough/2559
>
> at this point, this branch is pretty stable (imo). there shouldn't be any
> major changes between now and final release, but you might have to make a
> few adjustments to the gulpfile if you clone now
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/roots/roots/pull/1251#issuecomment-75051614>.
>


-- 
- Julien

**Comment by schrapel** [comment]
I've been using it to. I would recommend using it and paying attention to the future commits. You can make any changes manually if you need them.

**Comment by austinpray** [comment]
@conatus I am super interested in getting feedback at this stage so definitely try it out. I can personally walk you through any trouble you might have. Message me over at https://discourse.roots.io/ if you need something explained.

**Comment by conatus** [comment]
Cool. Well, I'll crack on using it as is and let you know on the Discourse if I find any problems.

**Comment by conatus** [comment]
:+1:

**Pull request merged**
