### PR TITLE
use correct editor-style.css filename for tinymce editor

### PR DESCRIPTION
**Pull request by gegere**
This fixes the admin side editor to use theme styles.

### CODE REVIEW

**Comment by retlehs** [comment]
thank you. please fix the code formatting issue pointed out by travis and we'll be good to merge!

**Comment by retlehs** [comment]
thx - can you also rebase to squash the commits? :wink:

**Comment by gegere** [comment]
Well that was fun, never used rebase before!

**Comment by austinpray** [comment]
@gegere :beers:

**Comment by retlehs** [comment]
sorry, one more thing. skip the variable and just use

```php
add_editor_style(Assets\asset_path('styles/editor-style.css'));
```

**Comment by gegere** [comment]
I had a feeling you might say this... correcting.

**Comment by gegere** [comment]
@austinpray we better connect around Austin next month so those beers can happen.

**Pull request merged**
