### PR TITLE
[WIP] Conditional tag check

### PR DESCRIPTION
**Pull request by swalkinshaw**
Simplify and generalize class since it had nothing to do directly with the sidebar. Now it can be used for other purposes as well.

### CODE REVIEW

**Comment by retlehs** [comment]
note to self - update new docs

**Comment by QWp6t** [comment]
I've actually been using the Sidebar class in this way for a while. I use it to determine whether to load a hero image (or other similar content). Oddly enough, it never really occurred to me to refactor it to make it more generic.

**Comment by JulienMelissas** [comment]
This is great - I've also used the class for lots of things, (like heros). +1

**Comment by swalkinshaw** [comment]
We had thought about it a while ago but mostly forgot about it. I think it was @Foxaii who had the idea.

I'm open to any better naming ideas as well although at least this one is explicit.

**Pull request merged**
