### PR TITLE
fix less breaking during watch on error

### PR DESCRIPTION
**Pull request by austinpray**
If the `--production` flag is set: hard fail the build if there is a
precompiler error. If unset, log an error and end the task
successfully.

fixes https://github.com/roots/roots/issues/1288

### CODE REVIEW

**Comment by austinpray** [comment]
@retlehs @JulienMelissas mind peeping this and seeing if it fixes the issue for you guys?

**Comment by JulienMelissas** [comment]
I can confirm this is working now, :zap: thanks @austinpray!

**Comment by austinpray** [comment]
ok should be rebased now

**Comment by retlehs** [comment]
:blue_heart:

**Pull request merged**
