### PR TITLE
Ref #1033 - better support for CPT templates

### PR DESCRIPTION
**Pull request by retlehs**
See #1033 

If your CPT is named `movie`:

* archive pages will attempt to load `templates/content-movie.php`
* single posts will attempt to load `templates/content-single-movie.php`

### CODE REVIEW

**Comment by kalenjohnson** [comment]
Me likey

**Comment by tiborp** [comment]
If we only had a 'like'button here ;-)

**Comment by fgilio** [comment]
+1 I like it

**Comment by ManuelRiveraC** [comment]
yupi!

**Comment by rslnk** [comment]
good one!

**Comment by cjmosure** [comment]
Nice +1

**Comment by mattiapaiano** [comment]
+ 1

**Pull request merged**
