### PR TITLE
Add namespace

### PR DESCRIPTION
**Pull request by retlehs**

### CODE REVIEW

**Comment by austinpray** [comment]
o͡͡͡͡͡͡͡͡͡͡͡͡͡͡╮(｡❛ᴗ❛｡)╭o͡͡͡͡͡͡͡͡͡͡͡͡͡͡

**Comment by retlehs** [comment]
ref #1192

**Comment by swalkinshaw** [comment]
We should use `__NAMESPACE__` for every namespace reference within the file so avoid repeating them.

**Comment by retlehs** [comment]
done - [L68 nav.php](https://github.com/roots/roots/blob/90979457de1170a4b12c1ed8f5df3bb3ea021e71/lib/nav.php#L68) is fine, right? and nothing needs to be changed in any template files?

**Comment by swalkinshaw** [comment]
[L68 nav.php](https://github.com/roots/roots/blob/90979457de1170a4b12c1ed8f5df3bb3ea021e71/lib/nav.php#L68) is correct yeah since it's referencing another namespace.

**Pull request merged**
