### PR TITLE
Adds JSCS for gulpfile and scripts

### PR DESCRIPTION
**Pull request by austinpray**
install JSCS globally npm install jscs -g
use `npm run jscs`

Now as far as actually fixing the issues.....

uses google styleguide: https://github.com/jscs-dev/node-jscs/blob/master/presets/google.json

### CODE REVIEW

**Comment by austinpray** [comment]
lol: https://travis-ci.org/roots/roots/jobs/48082617#L451

**Comment by retlehs** [comment]
you got an editorconfig plugin running? `.jscsrc` uses 4 spaces, needs to be 2

other than that, :+1:

**Comment by austinpray** [comment]
Huh? Jscsrc is 2 spaces

**Comment by retlehs** [comment]
currently it mixes them

**Comment by austinpray** [comment]
@retlehs u happy now or nah?

**Comment by retlehs** [comment]
yeah we might need something that tests json syntax for you next to get dat spacing right :+1:

**Pull request merged**
